FROM python:3.9-slim

WORKDIR /webapp

# Копируем код приложения и зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Запуск приложения
CMD ["python", "main.py"]